# Generated by Django 6.0 on 2025-12-14 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('surveys', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='distribution_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='groups.distributiongroup'),
        ),
        migrations.AddField(
            model_name='survey',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='themes.theme'),
        ),
        migrations.AddField(
            model_name='anonymousinvitation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_invitations', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveychoice',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='rankedchoiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_answers', to='surveys.surveychoice'),
        ),
        migrations.AddField(
            model_name='fivestonesanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones_answers', to='surveys.surveychoice'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankedchoiceanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_answers', to='surveys.surveyresponse'),
        ),
        migrations.AddField(
            model_name='fivestonesanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones_answers', to='surveys.surveyresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymousinvitation',
            unique_together={('survey', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='surveychoice',
            unique_together={('survey', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='rankedchoiceanswer',
            unique_together={('response', 'choice')},
        ),
        migrations.AlterUniqueTogether(
            name='fivestonesanswer',
            unique_together={('response', 'choice')},
        ),
    ]
