# Generated by Django 6.0 on 2025-12-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveychoice',
            name='url',
            field=models.URLField(blank=True, help_text='Optional URL to make this choice a clickable link', max_length=500),
        ),
    ]
