# Generated by Django 6.0 on 2025-12-14 18:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#4A5568', help_text='Primary brand color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#718096', help_text='Secondary accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(default='#48BB78', help_text='Accent/highlight color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(default='#F7FAFC', help_text='Background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#2D3748', help_text='Primary text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_secondary_color', models.CharField(default='#718096', help_text='Secondary text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', help_text='Font family for the theme', max_length=100)),
                ('heading_font_family', models.CharField(default='Inter, system-ui, sans-serif', help_text='Font family for headings', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default theme')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['name'],
            },
        ),
    ]
